"""Way of the Hunter species table: key -> (English, 中文, tier).
Keys are lowercase alphanumerics; matching is fuzzy (see extract.normalize_species)."""
SPECIES = {
    # Nez Perce Valley (USA)
    "whitetaildeer": ("Whitetail Deer", "白尾鹿", 5),
    "muledeer": ("Mule Deer", "騾鹿", 5),
    "rockymountainelk": ("Rocky Mountain Elk", "洛磯山馬鹿", 6),
    "elk": ("Rocky Mountain Elk", "洛磯山馬鹿", 6),
    "moose": ("Moose", "駝鹿", 6),
    "alaskamoose": ("Alaska Moose", "阿拉斯加駝鹿", 6),
    "pronghorn": ("Pronghorn", "叉角羚", 4),
    "bighornsheep": ("Bighorn Sheep", "大角羊", 5),
    "americanblackbear": ("American Black Bear", "美洲黑熊", 6),
    "blackbear": ("American Black Bear", "美洲黑熊", 6),
    "grizzlybear": ("Grizzly Bear", "灰熊", 6),
    "cougar": ("Cougar", "美洲獅", 5),
    "mountainlion": ("Cougar", "美洲獅", 5),
    "puma": ("Cougar", "美洲獅", 5),
    "coyote": ("Coyote", "郊狼", 4),
    "graywolf": ("Gray Wolf", "灰狼", 5),
    "greywolf": ("Gray Wolf", "灰狼", 5),
    "wolf": ("Gray Wolf", "灰狼", 5),
    "americanbadger": ("American Badger", "美洲獾", 3),
    "snowshoehare": ("Snowshoe Hare", "雪鞋兔", 1),
    "easternwildturkey": ("Eastern Wild Turkey", "東部野火雞", 1),
    "wildturkey": ("Eastern Wild Turkey", "東部野火雞", 1),
    "merriamswildturkey": ("Merriam's Wild Turkey", "梅里亞姆野火雞", 1),
    "turkey": ("Eastern Wild Turkey", "東部野火雞", 1),
    "rossgoose": ("Ross's Goose", "羅氏雁", 1),
    "rosssgoose": ("Ross's Goose", "羅氏雁", 1),
    "lesserscaup": ("Lesser Scaup", "小潛鴨", 1),
    "surfscoter": ("Surf Scoter", "斑頭海番鴨", 1),
    "wildduck": ("Wild Duck", "綠頭鴨", 1),
    "mallard": ("Wild Duck", "綠頭鴨", 1),
    # Transylvania
    "reddeer": ("Red Deer", "赤鹿", 6),
    "roedeer": ("Roe Deer", "狍", 4),
    "fallowdeer": ("Fallow Deer", "黇鹿", 5),
    "wildboar": ("Wild Boar", "野豬", 5),
    "boar": ("Wild Boar", "野豬", 5),
    "chamois": ("Chamois", "岩羚羊", 4),
    "mouflon": ("Mouflon", "歐洲盤羊", 4),
    "brownbear": ("Brown Bear", "棕熊", 6),
    "eurasianlynx": ("Eurasian Lynx", "歐亞猞猁", 4),
    "lynx": ("Eurasian Lynx", "歐亞猞猁", 4),
    "redfox": ("Red Fox", "赤狐", 3),
    "fox": ("Red Fox", "赤狐", 3),
    "goldenjackal": ("Golden Jackal", "金豺", 4),
    "eurasianbadger": ("Eurasian Badger", "歐亞獾", 3),
    "europeanbadger": ("Eurasian Badger", "歐亞獾", 3),
    "europeanhare": ("European Hare", "歐洲野兔", 1),
    "europeanrabbit": ("European Rabbit", "歐洲兔", 1),
    "pheasant": ("Pheasant", "雉雞", 1),
    "greylaggoose": ("Greylag Goose", "灰雁", 1),
    # Aurora Shores (Alaska)
    "barrengroundcaribou": ("Barren-Ground Caribou", "荒原馴鹿", 5),
    "caribou": ("Barren-Ground Caribou", "荒原馴鹿", 5),
    "woodbison": ("Wood Bison", "森林野牛", 6),
    "bison": ("Wood Bison", "森林野牛", 6),
    "kodiakbear": ("Kodiak Bear", "科迪亞克棕熊", 6),
    "sitkadeer": ("Sitka Deer", "錫特卡鹿", 5),
    "dallsheep": ("Dall Sheep", "白大角羊", 5),
    "muskox": ("Muskox", "麝牛", 6),
    "arcticfox": ("Arctic Fox", "北極狐", 3),
    "wolverine": ("Eurasian Wolverine", "狼獾", 4),
    "eurasianwolverine": ("Eurasian Wolverine", "狼獾", 4),
    "canadagoose": ("Canada Goose", "加拿大雁", 1),
    # Tikamoon Plains (Africa)
    "bluewildebeest": ("Blue Wildebeest", "藍角馬", 6),
    "blackwildebeest": ("Black Wildebeest", "黑角馬", 5),
    "gemsbok": ("Gemsbok", "南非劍羚", 6),
    "springbok": ("Springbok", "跳羚", 4),
    "impala": ("Impala", "黑斑羚", 4),
    "greaterkudu": ("Greater Kudu", "大扭角林羚", 6),
    "kudu": ("Greater Kudu", "大扭角林羚", 6),
    "capebuffalo": ("Cape Buffalo", "非洲水牛", 6),
    "lion": ("Lion", "獅子", 6),
    "leopard": ("Leopard", "花豹", 5),
    "spottedhyena": ("Spotted Hyena", "斑鬣狗", 5),
    "hyena": ("Spotted Hyena", "斑鬣狗", 5),
    "warthog": ("Warthog", "疣豬", 4),
    "blesbok": ("Blesbok", "白臉牛羚", 4),
    "plainszebra": ("Plains Zebra", "平原斑馬", 6),
    "zebra": ("Plains Zebra", "平原斑馬", 6),
    "blackbackedjackal": ("Black-backed Jackal", "黑背胡狼", 3),
    "honeybadger": ("Honey Badger", "蜜獾", 3),
    "egyptiangoose": ("Egyptian Goose", "埃及雁", 1),
    "helmetedguineafowl": ("Helmeted Guineafowl", "珠雞", 1),
    "guineafowl": ("Helmeted Guineafowl", "珠雞", 1),
    # Matariki Park (New Zealand)
    "sambardeer": ("Sambar Deer", "水鹿", 6),
    "sambar": ("Sambar Deer", "水鹿", 6),
    "sikadeer": ("Sika Deer", "梅花鹿", 5),
    "sika": ("Sika Deer", "梅花鹿", 5),
    "himalayantahr": ("Himalayan Tahr", "喜馬拉雅塔爾羊", 5),
    "tahr": ("Himalayan Tahr", "喜馬拉雅塔爾羊", 5),
    "rusadeer": ("Rusa Deer", "爪哇鹿", 5),
    "feralgoat": ("Feral Goat", "野山羊", 4),
    # Lintukoto Reserve (Finland)
    "reindeer": ("Reindeer", "馴鹿", 5),
    "forestreindeer": ("Finnish Forest Reindeer", "芬蘭森林馴鹿", 5),
    "capercaillie": ("Capercaillie", "松雞", 1),
    "blackgrouse": ("Black Grouse", "黑琴雞", 1),
    "mountainhare": ("Mountain Hare", "雪兔", 1),
    "raccoondog": ("Raccoon Dog", "貉", 3),
}

MAPS = {
    "nezperce": "Nez Perce Valley",
    "transylvania": "Transylvania",
    "alaska": "Aurora Shores",
    "aurora": "Aurora Shores",
    "africa": "Tikamoon Plains",
    "tikamoon": "Tikamoon Plains",
    "newzealand": "Matariki Park",
    "matariki": "Matariki Park",
    "finland": "Lintukoto Reserve",
    "lintukoto": "Lintukoto Reserve",
    "elkcrest": "Elkcrest Island",
}
